<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="PC1" failures="6" tests="34" name="rtestassuredtests" time="25.137" errors="0" timestamp="2022-10-06T17:13:40 EDT">
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="@BeforeClass deleteEmployee" time="0.583">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testCases.TC005_Delete_Employee_Record.deleteEmployee(TC005_Delete_Employee_Record.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:50)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 30 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployee -->
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="CheckContentLength" time="0.007">
    <failure type="java.lang.NumberFormatException" message="null">
      <![CDATA[java.lang.NumberFormatException: null
at java.base/java.lang.Integer.parseInt(Integer.java:614)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at com.employeeapi.testCases.TC001_Get_All_Employees.CheckContentLength(TC001_Get_All_Employees.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CheckContentLength -->
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkContentType" time="0.004"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkCookies" time="0.006"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkResponseBody" time="0.017"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkResponseTime" time="0.003"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkStatusCode" time="0.004"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkcontentEncoding" time="0.003"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkserverType" time="0.004"/>
  <testcase classname="com.employeeapi.testCases.TC001_Get_All_Employees" name="checkstatusLine" time="0.003"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkContentLength" time="0.003"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkContentType" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkResponseBody" time="0.002"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkStatusCode" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkserverType" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc002_GetSingle_Employee_Record" name="checkstatusLine" time="0.0"/>
  <testcase classname="com.employeeapi.testCases.Tc003_Post_Employee_Record" name="chechStatusLine" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.employeeapi.testCases.Tc003_Post_Employee_Record.chechStatusLine(Tc003_Post_Employee_Record.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- chechStatusLine -->
  <testcase classname="com.employeeapi.testCases.Tc003_Post_Employee_Record" name="checkContentType" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [application/json] but found [text/html; charset=UTF-8]">
      <![CDATA[java.lang.AssertionError: expected [application/json] but found [text/html; charset=UTF-8]
at com.employeeapi.testCases.Tc003_Post_Employee_Record.checkContentType(Tc003_Post_Employee_Record.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testCases.Tc003_Post_Employee_Record" name="checkResponseBody" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.testCases.Tc003_Post_Employee_Record.checkResponseBody(Tc003_Post_Employee_Record.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapi.testCases.Tc003_Post_Employee_Record" name="checkStatuscode" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.employeeapi.testCases.Tc003_Post_Employee_Record.checkStatuscode(Tc003_Post_Employee_Record.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatuscode -->
  <testcase classname="com.employeeapi.testCases.Tc003_Post_Employee_Record" name="checkcontentEncoding" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc003_Post_Employee_Record" name="checkserverType" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc004_PUT_Employee_Record" name="chechStatusLine" time="0.002"/>
  <testcase classname="com.employeeapi.testCases.Tc004_PUT_Employee_Record" name="checkContentType" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc004_PUT_Employee_Record" name="checkResponseBody" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.Tc004_PUT_Employee_Record" name="checkStatuscode" time="0.0"/>
  <testcase classname="com.employeeapi.testCases.Tc004_PUT_Employee_Record" name="checkcontentEncoding" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [br] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [br] but found [null]
at com.employeeapi.testCases.Tc004_PUT_Employee_Record.checkcontentEncoding(Tc004_PUT_Employee_Record.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkcontentEncoding -->
  <testcase classname="com.employeeapi.testCases.Tc004_PUT_Employee_Record" name="checkserverType" time="0.001"/>
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="chechStatusLine" time="0.0">
    <skipped/>
  </testcase> <!-- chechStatusLine -->
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="checkContentType" time="0.0">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="checkResponseBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="checkStatuscode" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatuscode -->
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="checkcontentEncoding" time="0.0">
    <skipped/>
  </testcase> <!-- checkcontentEncoding -->
  <testcase classname="com.employeeapi.testCases.TC005_Delete_Employee_Record" name="checkserverType" time="0.0">
    <skipped/>
  </testcase> <!-- checkserverType -->
</testsuite> <!-- rtestassuredtests -->
